Repository PrestaShop/prestashop-specs, pull requests merged in 2020-11, with the labels that each got.

#157 Create specs's page database
  back-office/advanced-parameters/database/advanced_parameters-database-sql_manager.md
Labels: Waiting for QA

#152 Create order settings specs
  back-office/shop-parameters/order-settings/order-settings.md
  img/Order as a guest.png
  img/Order_create_account.png
  img/Order_final_summary.png
  img/Reorder.png
  img/Reorder_detail.png
  img/minimum_order_value.png
Labels: Review required, Waiting for QA

#135 Add specs for BO menu tab
  back-office/advanced-parameters/menu/menu.md
Labels: Review required, Waiting for QA

#154 Add the overrides list to the Information specs
  back-office/advanced-parameters/information/information.md
Labels: Review required, Waiting for QA

#151 Add the free gift behavior in FO
  front-office/discounts/cart-rules-free-gift.md
Labels: Review required, Waiting for QA

#161 Specify the default language for order documents
  back-office/orders/orders/Order Page View.md
  front-office/customer-account.md
Labels: Review required, Waiting for QA

#163 Specify the Modules Manager > Updates page
  back-office/modules/module-manager/updates.md
Labels: Review required, Waiting for QA

#153 Update the product settings specifications
  back-office/shop-parameters/product-settings/Product Setting Page.md
  back-office/shop-parameters/product-settings/product-settings-page.md
  front-office/product-page.md
Labels: Waiting for QA

#165 Add SVG as accepted logo format
  back-office/design/themes-and-logo/theme-logo.md
Labels: Review required, Waiting for QA

#166 [multistore] - Add UAT for multistore
  back-office/multistoregeneralspecs.md
Labels: Ready for merge

#168 Update Order Page View.md
  back-office/orders/orders/Order Page View.md
Labels: Review required, Waiting for QA

#172 Edit Shop Parameters > Search
  back-office/shop-parameters/search/search.md
Labels: Ready for merge

#175 Add recycled packaging information
  front-office/checkout.md
Labels: Ready for merge

#177 Add link for product images in product listing
  back-office/catalog/products/catalog-products-listing.md
Labels: Ready for merge

#178 Update Order Page View.md
  back-office/orders/orders/Order Page View.md
Labels: Review required

#174 add specs for round on each item
  broader-topics/price-calculation-rules.md
Labels: Ready for merge
