Repository PrestaShop/prestashop-specs, pull requests merged in 2020-10, with the labels that each got.

#137 Add links to the repository tree
  README.md
Labels: Repository mgmt

#134 [WIP] Add specifications about thumbnails regeneration
  back-office/design/image-settings/regenerate-thumbnails.md
Labels: WIP

#150 Update the link of the product team in the readme
  README.md
Labels: Repository mgmt

#142 Add specs for stock management
  back-office/shop-parameters/product-settings/Product Setting Page.md
Labels: Review required

#141 Add specs for gift wrapping message
  back-office/orders/orders/Order Page View.md
Labels: Review required

#140 Add missing Shipping specs
  back-office/orders/orders/Order Add/Add new Order.md
Labels: Review required

#156 Specify the FO behavior at the payment step
  front-office/checkout.md
Labels: Review required
