Repository PrestaShop/prestashop-specs, pull requests merged in 2021-12, with the labels that each got.

#265 SimonasB88 - Images for specs
  static/img/image-settings-add-edit-image-type.png
  static/img/image-settings-bulk-actions.png
  static/img/image-settings-image-settings.png
  static/img/image-settings-images-generation-options.png
  static/img/image-settings-regenerate-thumbnails.png
Labels: Review required, Ready for merge

#263 Create specs for stores pages
  content/1.7/back-office/shop-parameters/contact/stores/_index.md
  content/1.7/back-office/shop-parameters/contact/stores/add-edit-store.md
  content/1.7/back-office/shop-parameters/contact/stores/stores-listing.md
Labels: PM ✔️, QA ✔️

#269 Create search-listing.md
  content/1.7/back-office/shop-parameters/search/add-edit-alias.md
  content/1.7/back-office/shop-parameters/search/search-listing.md
Labels: QA ✔️

#281 Update multistore specs share orders
  content/1.7/back-office/advanced-parameters/multistore/multistore.md
Labels: Waiting for PM, Review required
