Repository PrestaShop/prestashop-specs, pull requests merged in 2021-01, with the labels that each got.

#194 Create a checklist
  CHECKLIST.md
Labels: Ready for merge, Repository mgmt

#193 Add multistore behavior for catalog price rule
  back-office/catalog/discount/catalog-price-rules.md
Labels: Ready for merge

#191 Add missing specs for sql manager page
  back-office/advanced-parameters/database/advanced_parameters-database-sql_manager.md
Labels: Ready for merge

#200 Specify empty search results behaviors
  front-office/search.md
Labels: Ready for merge

#199 Add translation workflow
  back-office/international/translations/translations.md
Labels: Ready for merge

#202 Update the specs for empty search results
  front-office/search.md
Labels: Ready for merge

#197 Add #9561 warning notification
  installer/installer.md
Labels: Review required, Waiting for dev

#187 Create specs for customer service dashboard
  back-office/customer-service/customer-service/dashboard.md
Labels: Ready for merge

#195 Update theme & logo specs
  back-office/design/themes-and-logo/theme-logo.md
Labels: Ready for merge

#196 Add #19200 improvement to the Order page specifications
  back-office/orders/orders/Order Page View.md
Labels: Ready for merge

#186 Specify the Customer Settings pages
  back-office/shop-parameters/customer-settings/customers.md
  back-office/shop-parameters/customer-settings/groups.md
  back-office/shop-parameters/customer-settings/titles.md
  front-office/checkout.md
  front-office/customer-account.md
Labels: Ready for merge
