Repository PrestaShop/prestashop-specs, pull requests merged in 2022-10, with the labels that each got.

#347 Specs cross-selling
  content/1.7/modules/cross-selling.md
Labels: Review required

#346 Link Widget (List Widget)
  content/1.7/back-office/design/link-widget/link-widget-listing.md
  static/img/link-widget.png
Labels: Review required

#343 Specs contact information
  content/1.7/modules/contact-information.md
Labels: Review required

#342 Specs payments by check
  content/1.7/modules/payments-by-check.md
Labels: Review required

#340 Specs bank transfer module
  content/1.7/modules/bank-transfer.md
Labels: Review required

#338 Specs titles
  content/1.7/back-office/shop-parameters/customer-settings/add-edit-social-titles.md
  content/1.7/back-office/shop-parameters/customer-settings/view-titles.md
Labels: Waiting for author

#337 Advanced parameters - DB Backup
  content/1.7/back-office/advanced-parameters/database/configure-database-backup.md
  static/img/configure-db-backup.png
Labels: Review required

#336 Advanced parameters - Administration
  content/1.7/back-office/advanced-parameters/administration/configure-administration.md
  static/img/configure-administration.png
  static/img/new-customer.png
  static/img/new-messages.png
  static/img/notifications-dropdown-block.png
Labels: Review required

#335 Specs customer settings
  content/1.7/back-office/shop-parameters/customer-settings/add-new-group.md
  content/1.7/back-office/shop-parameters/customer-settings/edit-customer.md
  content/1.7/back-office/shop-parameters/customer-settings/edit-group.md
  content/1.7/back-office/shop-parameters/customer-settings/view-customer-settings.md
  content/1.7/back-office/shop-parameters/customer-settings/view-group.md
  content/1.7/back-office/shop-parameters/customer-settings/view-groups.md
Labels: Waiting for author

#333 Credit notes specs
  content/1.7/back-office/orders/credit-slips/view-credit-notes.md
Labels: Review required

#332 Delivery slips
  content/1.7/back-office/orders/delivery-slips/view-delivery-slips.md
Labels: Waiting for author

#331 specs-invoices
  content/1.7/back-office/orders/invoices/view-invoices.md
Labels: Waiting for author

#329 Specs profiles
  content/1.7/back-office/advanced-parameters/team/add-edit-profile.md
  content/1.7/back-office/advanced-parameters/team/view-profiles.md
Labels: Review required

#323 Specs-logs
  content/1.7/back-office/advanced-parameters/logs/view-logs.md
Labels: Review required

#322 Specs localization
  content/1.7/back-office/international/localization/add-edit-language.md
  content/1.7/back-office/international/localization/view-geolocation.md
  content/1.7/back-office/international/localization/view-languages.md
Labels: Review required

#321 Payment preferences
  content/1.7/back-office/payment/preferences/view-preferences.md
Labels: Review required

#315 Specs categories
  content/1.7/back-office/catalog/categories/add-edit-category.md
  content/1.7/back-office/catalog/categories/view-categories.md
Labels: Review required

#314 Specs general settings
  content/1.7/back-office/shop-parameters/general/view-general.md
Labels: Review required

#313 Performance tab
  content/1.7/back-office/advanced-parameters/performance/view-performance.md
Labels: Review required

#312 Update information.md
  content/1.7/back-office/advanced-parameters/information/information.md
Labels: Review required

#311 Stock specs
  content/1.7/back-office/catalog/stock/_index.md
  content/1.7/back-office/catalog/stock/view-movement.md
  content/1.7/back-office/catalog/stock/view-stock.md
Labels: Review required

#310 Delivery Slips
  content/1.7/back-office/orders/invoices/configure-delivery-slips.md
  content/1.7/back-office/orders/invoices/configure-invoices.md
  content/1.7/back-office/orders/orders/shopping-carts-listing.md
  content/1.7/back-office/orders/orders/view-shopping-cart.md
  static/img/orders-delivery-slips.png
  static/img/orders-invoices.png
  static/img/orders-shopping-cart.png
  static/img/orders-shopping-carts-bulk-actions.png
  static/img/orders-shopping-carts-view-shopping-cart.png
Labels: Review required

#308 Specs brands and suppliers
  content/1.7/back-office/catalog/brands-and-suppliers/add-edit-brand-address.md
  content/1.7/back-office/catalog/brands-and-suppliers/add-edit-brand.md
  content/1.7/back-office/catalog/brands-and-suppliers/brands-and-suppliers-brands.md
  content/1.7/back-office/catalog/brands-and-suppliers/view-brand.md
Labels: Review required

#307 Modules
  content/1.7/back-office/modules/module-catalog/module-selections.md
  content/1.7/back-office/modules/module-manager/alerts-and-updates-listing.md
  content/1.7/back-office/modules/module-manager/modules-listing.md
  static/img/alerts-listing.png
  static/img/module-selections.png
  static/img/modules-listing.png
  static/img/updates-listing.png
Labels: Review required

#300 Customers specs
  content/1.7/back-office/customers/customers/add-edit-customer.md
  content/1.7/back-office/customers/customers/customers-listing.md
  content/1.7/back-office/customers/customers/view-customer.md
Labels: Review required

#299 Add 410 gone to specs
  content/1.7/back-office/catalog/products/add-edit.md
Labels: Ready for merge

#298 Traffic & SEO
  content/1.7/back-office/shop-parameters/traffic-and-seo/add-edit-search-engine.md
  content/1.7/back-office/shop-parameters/traffic-and-seo/search-engines-listing.md
  static/img/traffic-and-seo-add-edit-search-engine.png
  static/img/traffic-and-seo-search-engines.png
Labels: Review required

#297 Outstanding
  content/1.7/back-office/customers/customers/outstanding-listing.md
  static/img/customers-outstanding.png
Labels: Review required

#296 addresses-specs
  content/1.7/back-office/customers/addresses/add-edit-addresses.md
  content/1.7/back-office/customers/addresses/add-edit.md
  content/1.7/back-office/customers/addresses/addresses-listing.md
Labels: Review required

#293 Specs countries
  content/1.7/back-office/international/locations/countries/_index.md
  content/1.7/back-office/international/locations/countries/add-edit-country.md
  content/1.7/back-office/international/locations/countries/countries-listing.md
Labels: Waiting for PM, Review required, PM ✔️

#292 SimonasB88 - Taxes
  content/1.7/back-office/international/taxes/add-edit-tax-rules.md
  content/1.7/back-office/international/taxes/add-edit-taxes.md
  content/1.7/back-office/international/taxes/international-tax-rules-listing.md
  content/1.7/back-office/international/taxes/taxes-listing.md
  static/img/international-add-edit-tax-rules.png
  static/img/international-add-edit-taxes.png
  static/img/international-tax-rules.png
  static/img/international-taxes.png
Labels: Waiting for PM, Waiting for author, Review required

#286 Dashboard specs
  content/1.7/back-office/dashboard/_index.md
  content/1.7/back-office/dashboard/dashboard-configure.md
  content/1.7/back-office/dashboard/dashboard.md
Labels: Waiting for PM, Review required, PM ✔️

#285 SimonasB88 - Import
  content/1.7/back-office/advanced-parameters/import/configure-import.md
  static/img/advanced-parameters-import-success-popup.png
  static/img/advanced-parameters-import.png
  static/img/product-import-match-your-data.png
Labels: Review required

#274 Simonas B88 - Login
  content/1.7/back-office/login.md
  static/login.png
Labels: Waiting for PM, Waiting for author

#266 SimonasB88 - Design Positions
  content/1.7/back-office/design/positions/transplant-a-module-listing.md
  content/1.7/back-office/design/positions/view-positions.md
  static/img/design-positions-transplant.png
  static/img/design-positions.png
Labels: Waiting for PM

#88 [WIP]Specs for breadcrumbs in Front-office
  front-office/breadcrumbs.md
Labels: Waiting for PM, Waiting for UX, WIP

#170 [WIP] Add split order use cases
  broader-topics/split-order.md
Labels: Help wanted, WIP

#246 Cart Rules + Catalog Price Rules
  content/1.7/back-office/catalog/discount/add-edit-cart-price-rule.md
  content/1.7/back-office/catalog/discount/add-edit-catalog-price-rule.md
  content/1.7/back-office/catalog/discount/cart-rules-listing.md
  content/1.7/back-office/catalog/discount/view-catalog-price-rules.md
  static/img/cart-rules-restriction-product-select.png
Labels: Review required, Waiting for QA
